name: mobile_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  speech_to_text: ^7.0.0
  flutter_tts: ^3.8.3
  permission_handler: ^11.0.0
  google_fonts: ^6.1.0
  animate_do: ^3.0.2
  flutter_spinkit: ^5.2.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.0.0
  syncfusion_flutter_gauges: ^24.1.41
  supabase_flutter: ^2.3.0
  shared_preferences: ^2.2.2
  introduction_screen: ^3.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
